### ISSUE TITLE
It`s Failed to parse Insert statement in 1.30.0 version

### ISSUE THREAD

**Issue by weijunlu** [vvysotskyi/drill-calcite#12]
1， pom.xml configuration
<dependency>
                <groupId>org.apache.calcite</groupId>
                <artifactId>calcite-core</artifactId>
                <version>1.30.0</version>
            </dependency>
2, the parser demo is as follows:
 public static void main(String[] args) throws Exception {
        String sql = "inset into test.t1 (c1, c2) values (1,1)";

        SqlParser.Config config = SqlParser.config()
                .withParserFactory(SqlParserImpl.FACTORY);

        SqlParser parser = SqlParser.create(sql, config);
        SqlNode sqlNode = parser.parseStmt();
        System.out.println(sqlNode);
    }

3. The error message is as follows:
Caused by: org.apache.calcite.runtime.CalciteException: Non-query expression encountered in illegal context
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:932)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:917)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.checkNonQueryExpression(SqlParserImpl.java:312)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.Expression3(SqlParserImpl.java:16502)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.Expression2b(SqlParserImpl.java:16155)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.Expression2(SqlParserImpl.java:16196)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.Expression(SqlParserImpl.java:16126)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.LeafQueryOrExpr(SqlParserImpl.java:16103)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.QueryOrExpr(SqlParserImpl.java:15557)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.OrderedQueryOrExpr(SqlParserImpl.java:505)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.SqlStmt(SqlParserImpl.java:3790)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.SqlStmtEof(SqlParserImpl.java:3828)
	at org.apache.calcite.sql.parser.impl.SqlParserImpl.parseSqlStmtEof(SqlParserImpl.java:201)
        at org.apache.calcite.sql.parser.SqlParser.parseQuery(SqlParser.java:158)
	... 2 more

**Comment by weijunlu** [comment]
Sorry, The insert sql that i wrote is error.
